import React from 'react'
import Message from './Message'

const Conversation = ({id,title, content}) =>{

  //The conversation title will be generated by ChatGPT 3 API
  //The conversation contents is the messages between the user and the chatbot
  //The conversation id is the id of the conversation in the database(mongoDB)


  //Here is the function to generate conversation title by ChatGPT 3 API based on the conversation content
  const generateTitle = () =>{
    //TODO
  }

  
  
  return (
    <div>
      <h1>{id}</h1>
      <h1>{title || null}</h1>
      {
        content.map((message, index) => {
          return (
            <Message
              key={index}
              userMessage={message.userMessage}
              botResponse={message.botResponse}
              userMessageUniqueID={message.userMessageUniqueID}
              botMessageUniqueID={message.botMessageUniqueID}
            />
          )
        }
        )
      }
    </div>
  )
}

export default Conversation;